# Generated by Django 3.2 on 2021-05-16 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210516_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='data',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 16, 20, 24, 40, 221497, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
